//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesWebApp.Entitymodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVCMOVIECAST
    {
        public int ACTID { get; set; }
        public int MOVID { get; set; }
        public string ROLE { get; set; }
    
        public virtual MVCACTOR MVCACTOR { get; set; }
        public virtual MVCMOVy MVCMOVy { get; set; }
    }
}
