//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesWebApp.Entitymodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVCMOVy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MVCMOVy()
        {
            this.MVCMOVIECASTs = new HashSet<MVCMOVIECAST>();
        }
    
        public int MOVID { get; set; }
        public string MOVTITLE { get; set; }
        public Nullable<int> MOVYEAR { get; set; }
        public string MOVLANG { get; set; }
        public Nullable<int> DIRID { get; set; }
        public string Image { get; set; }
    
        public virtual MVCDIRECTOR MVCDIRECTOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MVCMOVIECAST> MVCMOVIECASTs { get; set; }
    }
}
